### ISSUE TITLE
Userstory 1 - Create the price info and the list of bikes

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project-havana-bikes#1]
## Value Proposition

**As a** User,
**I want to** see the price and a list of bikes,
**so that** I can see which of them I will choose.
​

## Description

![Image](https://user-images.githubusercontent.com/53151968/213703927-4356a850-f859-42b6-8082-a3bcd69b81ed.png)
​

## Acceptance Criteria

- [ ] The prices are displayed,
- [ ] The user should be able to see a preview of some bikes and the "...Show more" link to "Bikes",
- [ ] On clicking "...Show more" the user should be able to navigate to the page "Bikes" where a list of bikes is displayed.
- [ ] On clicking "Home", the user should be able to navigate back to "Home" from the page "Bikes".
      ​

## Tasks

- [x] Create the Component to display the prices and other infos like open / close time, etc... in a section "Price",
- [x] Create a json file with an array of all the bikes, with characteristics and link to their respectively foto,
- [x] Create the Component "BikesPreview" with 2 or 3 fotos as a preview and a link to a new page "Bikes",
- [x] Create the new page "Bikes", 
- [x] Create a new component "BikesList" and return it in the page "Bikes", 
- [x] In the component "BikesList", map over the array of all the bikes and return the list of the bikes in this page "Bikes",
- [x] Create the link to get back to "Home",
- [x] Create the Component for the Header.
      ​

## Complexity

L
