### ISSUE TITLE
Userstory 7 - Add button "Book" with functionality

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project-havana-bikes#14]
## Value Proposition

**As a** User,
**I want to** see the button "Book",
**so that** I can book the bikes. 

## Description

The button "Book" is displayed as disable while there is no bikes or no date selected. When there is bikes and date selected, the button is display as active. Clicking this button will display a toast notification confirming that the booking was successful, the form will be reseted and it will get the shopping cart empty.

![Bildschirmfoto 2023-02-07 um 12 53 07](https://user-images.githubusercontent.com/53151968/217237865-588f677e-9c83-4122-b849-ab774a244227.png)

## Acceptance Criteria

- [ ] A button "Book" is displayed on page "ShoppingCartPage",
- [ ] The button "Book" is disable if there is no selected bikes or no date,
- [ ] The button "Book" is active if there is bikes and date selected,
- [ ] A toast notification  message (Booking successful) is displayed when clicking this button.

## Tasks

- [ ] Create the button "Book" inside the form "LeaseTimeForm",
- [ ] Add functionality to the button so that it is disable when there is no bikes or no booking date selected,
- [ ] Add functionality to the button so that when clicking on it, 
   - [ ] ...it resets the data from the form "LeaseTimeForm",
   - [ ] ...it empty the shopping cart, and...
   - [ ] ...it displays a toast notification of confirmation that the booking was successful.

## Complexity

M

**Comment by HosseinKrouna** [comment]
Hi Yuri,

I think you wanted to say in your description that the button is hidden until both (date and bike) have been selected. Instead of or.

In your acceptance criteria you write once is disabled if either bike or date is selected.
The active status of your booking button is logical for me.
But does it make sense to be disabled to book if one of them is missing?
You should think i'm wrong about that, If you want you can explain it to me in more detail ;)

Maybe you want to lead your user back to your homepage after booking. But now it wouldn't be a reason.

**Comment by YuriPadilla** [comment]
Hi Hossein!!! Thanks a lot for your review and for your time!!!  :)  :)  :)

In my description I wanted to say exact what I said: _"...disable..."_ and not hidden. I mean, the user can see the button, but it is no possible to click on it until both (date and bike) have been selected. So... if only one input, bikes _"or"_ date is missing, then the button is disable. Even in the Excalidraw image it is possible to see that the color of the button is a light gray which indicates it is disable.

In my acceptance criteria I said that the button is _disable_ if bikes _"or"_ date are not selected. I think _"or"_ is right...!!!

For sure it makes sense this button to be disable to book if only one of them is missing!!! _BOTH_ inputs are needed!!!
- It is no possible to rent a bike without the date for renting, (Otherwise, how many days for booking the bike(s) then? ...1, 2 or 1000 days? 😉)
- And it is no possible to rent a bike without selecting the bike(s) for renting (Otherwise, what is going to be rented then? ...a room? ...a car? ...a plane? 😉).

About leading the user back to the homepage after booking, that is a good idea, maybe I will do something similar! 😀

Thanks again for your review, Hossein!!! Many greetings to you!!! 😀 👍

**Comment by HosseinKrouna** [comment]
haha 😅 I actually meant "disable"... yesterday I probably had a mistake in thinking

I was just wondering because in your acceptance criteria you say that, the button is disabled if Bikes or Date are not selected.
What happens if both is not selected?
I would understand that you could then book even though "both" inputs would be missing. But I could be wrong about that too

Anyway, I think these are small things, so we don't have to deal with them any longer and I'm happy to give you a go for your user story 😀👍

**Comment by YuriPadilla** [comment]
Hey Hossein! Nice to hear from you! ...And thanks for your comment! 😀

To your question: _"What happens if both is not selected?"_, _if both (bikes or date) are not selected (at the same time)_, it means that at least one of them is not selected, and _if_ so, then it is no possible to rent/book... so here again, the _"or"_ word is right here. 

- At least just one input is not filled out then it is no possible to book... easy! 😀
- When both inputs (bikes and date) are not filled out at the same time, it has implicit that at least one of them is not selected, so again... no possible to book... easy! 😀

To be able to rent a bike, both of the inputs must be selected bikes _"and"_ date.

If you don't understand the _logic_, then you can read the description again
