### ISSUE TITLE
Userstory 8 - Create a Navigation Bar

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project-havana-bikes#15]
## Value Proposition

**As a** User,
**I want to** see a navigation bar ,
**so that** I can navigate easier between pages.

## Description

![Bildschirmfoto 2023-02-07 um 16 21 22](https://user-images.githubusercontent.com/53151968/217286389-9459e334-1e5e-47db-b383-28c2e6eb6f66.png)

## Acceptance Criteria

- [ ] A navigation bar is display,
- [ ] Clicking on an icon opens the respective page,
- [ ] The respective icon is highlighted depending on the current page.

## Tasks

- [ ] Create the component "NavBar" which returns a `<nav>` element,
- [ ] Display this component "NavBar" on every page,
- [ ] Add a link on every icon to its respective page,
- [ ] Implement a highlight functionality, so that the respective icon is highlighted depending on the respective page.

## Complexity

M

**Comment by marcterre** [comment]
Hey Yuri, in your acceptance criteria you should describe which icon you use for which page and if its a Link or a Button (like you did in your tasks).
The rest looks good, i like the wireframes! 👍

**Comment by YuriPadilla** [comment]
Hi Marc! Thanks for your review!!!

I've already updated it...!!!  

Many greetings to you! 😀👍
