### ISSUE TITLE
Userstory 9 - Add backend

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project-havana-bikes#18]
## Value Proposition

**As a** User,
**I want to** access to the same data from a database,
**so that** I can see all the available products on different devices.

## Description

Create a database in MongoDB Atlas to be able to see all the bikes available from anywhere and from any device.

## Acceptance Criteria

- [ ] All bikes from a the database in the cloud are displayed on pages:
   - [ ] Home in the (preview), Bikes, Bikes Details, Shopping Cart.

## Tasks

- [ ] Create database on MongoDB Atlas,
- [ ] Prepare the database connection
- [ ] 
- [ ] 
- [ ] Create a database function to `find` all places
- [ ] Create an api endpoint in your `api/places` route for fetching all places from the database
- [ ] Map over the fetched places to render the cards

## Complexity

M

**Comment by magjo21** [comment]
Hi,
LGTM
