### ISSUE TITLE
Userstory 2 - Add contact info

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project-havana-bikes#2]
## Value Proposition

**As a** User,
**I want to** see the contact info,
**so that** I can contact them for booking a bike and for asking questions.
​

## Description

![Image](https://user-images.githubusercontent.com/53151968/213783191-8bc5c1d6-449e-44dd-9fa7-39c9e8291f46.png)

## Acceptance Criteria

- [ ] The contact information is displayed,
- [ ] A button "Contact us" is displayed,
- [ ] The button "Contact us" displays a form in a new page "Contact us",
- [ ] The form contains: input "name" (required), input "email" (required), text-area "message" (required), 
- [ ] The form contains also: a submit button "Send", a button "Cancel" and a button "<- Back" to get back to "Home",
- [ ] The button "Send" sends the message to Havana Bikes, get the page "Home" again, and a confirmation is showed.
- [ ] The confirmation display the message: "your message was sent",
- [ ] The button "Cancel" gets back to "Home" without sending the message.
      ​

## Tasks

- [ ] Create the Component "ContactInfo" with the necessary contact information and include it in "Home",
- [ ] Create component "Button" and... 
- [ ] use it to add the button "Contact us" in the Component "ContactInfo"
- [ ] Add logic to "Contact us" to open a new page "ContactUsPage",
- [ ] Create the page "ContactUsPage", where a form will be displayed,
- [ ] Create component "ContactUsForm" and use it in the page "ContactUsPage",
- [ ] Add to the form in page "ContactUsPage":  input "name" (required), input "email" (required), textarea "message" (required), a submit button "Send" and a button "<- Home".
- [ ] Add logic and functionality to the button "<- Back",
- [ ] Add logic and functionality to the button "Send" (first just to get a notification that the message was sent. I'll work some day later on the logic to really send an email with _"SendGrid"_).
​

## Complexity

L

**Comment by AGeck113** [comment]
Looks really big, but it has a clear structure. Maybe it is big enough to split it in 2? If you want to do it in this big one it's fine, just as an option.
