### ISSUE TITLE
Userstory 10 - Add styles

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project-havana-bikes#20]
## Value Proposition

**As a** User,
**I want to** see a nice and clear UI,
**so that** it is easier to understand and navigate through the WebApp. 

## Description

Implement a responsive design using responsive units and set general css-variables to use all over the WebApp in order to get a more intuitive one which is able to be used in every mobile device.

## Acceptance Criteria

- [ ] All pages must be responsive styled.

## Tasks

- [ ] Style page "Home" with responsive units,
- [ ] Style page "Info" with responsive units,
- [ ] Style page "Bikes" with responsive units,
- [ ] Style page "Bikes Details" with responsive units,
- [ ] Style page "Contact us" with responsive units,
- [ ] Style page "Shopping Cart" with responsive units,
- [ ] Set general css-variables for colors and implement them.

## Complexity

XL
