### ISSUE TITLE
Userstory 11 - Create a unique component to replace for all those component which repeats

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project-havana-bikes#22]
## Value Proposition

**As a** developer,
**I want to** have a unique piece of code (in form of a component or styled component),
**so that** I can use it everywhere when I need it.

## Description

In the code all over the pages and components, there is a lot of parts of the code which are the same, and it repeats again and again, like buttons, next/links, sections, headings h3, etc... The Object of this Userstory is to find those unnecessary repetitions of code and a create a respectively component (or styled component) to use it there instead where is need it.

## Acceptance Criteria

- [ ] 

## Tasks

- [ ] Create a styled component "StyledLinkAsButton" which is a link with a function as button and use it there where is need it,
   - [ ] Write this "StyledLinkAsButton" in: components/Button/Button.styled,
   - [ ] Use this "StyledLinkAsButton" in: PriceInfo, BikesPreview, ContactInfo,
- [ ] Create a styled component "StyledButton" which is a button and use it there where is need it,
   - [ ] Write this "StyledButton" in: components/Button/Button.styled,
   - [ ] Use this "StyledButton" in: ProductDetails, ContactUsForm, SelectedProducts, LeaseTimeForm,
- [ ] Create a styled component "StyledHeadingH3" which is a styled h3 and a `<hr />` and use it as heading for all sections,
- [ ] Create a styled component "StyledSection" which is a styled section and use it for all sections.

## Complexity

M
