### ISSUE TITLE
Userstory 12 - Add responsive disign

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project-havana-bikes#25]
## Value Proposition

**As a** User
**I want to** see a UI which is able to get adjusted to all mobile displays
**so that** it is easier to understand and navigate through the WebApp.

## Description

Implement a responsive design using responsive units and set general css-variables to use them all over the WebApp in order to get a more intuitive one, which is able to be used in every mobile device.

## Acceptance Criteria

- [ ] All pages must be responsive styled.

## Tasks

- [ ] Style page "Home" (landing page) with responsive units,
- [ ] Style page "InfoPage" with responsive units,
- [ ] Style page "Bikes" with responsive units,
- [ ] Style page "Bikes Details" with responsive units,
- [ ] Style page "Contact us" with responsive units,
- [ ] Style page "Shopping Cart" with responsive units,
- [ ] Set general css-variables for colors and implement them.

## Complexity

XL
