### ISSUE TITLE
Userstory 3 - Add list of bike parts

### ISSUE THREAD

**Issue by YuriPadilla** [YuriPadilla/capstone-project-havana-bikes#3]
## Value Proposition

**As a** User,
**I want to** see a list of bike parts,
**so that** I can see which of them I will choose.
​

## Description

![Image](https://user-images.githubusercontent.com/53151968/213729728-f2f54faa-bae0-4087-bee9-ea668af3edb2.png)

## Acceptance Criteria

- [ ] The user should be able to see a preview of some bike parts and the "...Show more" link to "Bikes",
- [ ] On clicking "...Show more" the user should be able to navigate to the page "Bike Parts" where a list of bike parts is displayed.
- [ ] On clicking "Home", the user should be able to navigate back to "Home" from the page "Bikes".
      ​

## Tasks

- [ ] Create a json file with an array of all the bike parts, with characteristics and link to their respectively foto,
- [ ] Create the component "BikePartsPreview" with 2 or 3 bike parts fotos displayed as a preview and a link "...Show all" to the new page "BikeParts",
- [ ] Add this component "BikePartsPreview" to "Home" with the bike parts list as prop,
- [ ] Create the new page "BikeParts",
- [ ] Create a new component "BikePartsList" and return it in the page "BikeParts",
- [ ] In the component "BikePartsList", map over the array of all the bike parts and return the list of the bike parts in this page "BikeParts",
- [ ] Create the link to get back to "Home".
      ​

## Complexity

M
